Vector and Matrix operations
Denigmma/spbu-python-course pull request #1
Opened 2024-09-26 18:30 UTC by Denigmma

Operations on vectors are implemented: scalar product, vector length, angle between vectors.
Operations on matrices are implemented: addition, multiplication, transposition.
Added tests for the covering functionality.
It is configured to run tests using pytest in .github/workflows/.
Static type checking is configured using mypy in .github/workflows/.

2024-09-30 15:05 UTC, Krekep requested changes
В целом хорошо, но необходимы исправления

2024-09-30 15:05 UTC, Krekep commented on tests/test_operations_on_vectors.py
> +    )  # π/2 radians
Тесты не репрезентативны, на каждую операцию необходимо несколько разных тестов (проверяющих разные свойства), в том числе граничные ситуации

2024-09-30 19:37 UTC, Denigmma commented on tests/test_operations_on_vectors.py
> +    )  # π/2 radians
Добавил несколько тестов на каждую операцию, включающие в себя проверку на граничные значения (нулевые, ошибочные и тд). Так же добавил тесты на операции с векторами с плавающей запятой.

2024-09-30 19:37 UTC, Denigmma commented on tests/test_operations_on_matrix.py
> +def test_matrix_multiplication():
Добавил тесты.

2024-09-30 19:37 UTC, Denigmma commented on tests/test_operations_on_matrix.py
> +    assert transpose_matrix(m) == expected_result
Поправил недочет. Теперь при операциях над целочисленными матрицами, а так же при операциях над матрицами, содержащие числа с плавающей запятой - получаем корректные ответы.

2024-10-01 09:03 UTC, Krekep approved these changes
Зачтено

2024-10-01 09:03 UTC, Krekep commented on project/matrix_operations.py
> +    """
Рекомендую ознакомиться с typing.Union

2024-10-04 12:58 UTC, merged